const SWITCH_UNIT = 'SWITCH_UNIT';
const LOAD_FORECAST = 'LOAD_FORECAST';
const FORECAST_LOADED = 'FORECAST_LOADED';
const LOAD_FORECAST_ERROR = 'LOAD_FORECAST_ERROR';
const NEXT = 'NEXT';
const PREVIOUS = 'PREVIOUS';

export default { SWITCH_UNIT, LOAD_FORECAST, FORECAST_LOADED, LOAD_FORECAST_ERROR, NEXT, PREVIOUS }